<?php

return [
	'jsonadm' => [
		'partials' => [
			'catalog' => [
				'template-data' => 'partials/catalog/data-standard',
			],
			'locale' => [
				'site' => [
					'template-data' => 'partials/locale/site/data-standard',
				],
			],
			'order' => [
				'template-data' => 'partials/order/data-standard',
				'template-included' => 'partials/order/included-standard',
				'base' => [
					'template-data' => 'partials/order/base/data-standard',
				],
			],
		],
		'domains' => [
			'attribute' => 'attribute',
			'catalog' => 'catalog',
			'coupon' => 'coupon',
			'customer' => 'customer',
			'index' => 'index',
			'locale' => 'locale',
			'media' => 'media',
			'order' => 'order',
			'plugin' => 'plugin',
			'price' => 'price',
			'product' => 'product',
			'rule' => 'rule',
			'service' => 'service',
			'supplier' => 'supplier',
			'stock' => 'stock',
			'tag' => 'tag',
			'text' => 'text',
		],
		'resources' => [
			'attribute/type' => 'attribute/type',
			'attribute/lists/type' => 'attribute/lists/type',
			'attribute/property/type' => 'attribute/property/type',
			'catalog/lists/type' => 'catalog/lists/type',
			'coupon/config' => 'coupon/config',
			'customer/lists/type' => 'customer/lists/type',
			'customer/property/type' => 'customer/property/type',
			'media/type' => 'media/type',
			'media/lists/type' => 'media/lists/type',
			'media/property/type' => 'media/property/type',
			'plugin/config' => 'plugin/config',
			'plugin/type' => 'plugin/type',
			'price/type' => 'price/type',
			'price/lists/type' => 'price/lists/type',
			'price/property/type' => 'price/property/type',
			'product/type' => 'product/type',
			'product/lists/type' => 'product/lists/type',
			'product/property/type' => 'product/property/type',
			'rule/config' => 'rule/config',
			'rule/type' => 'rule/type',
			'service/config' => 'service/config',
			'service/type' => 'service/type',
			'service/lists/type' => 'service/lists/type',
			'supplier/lists/type' => 'supplier/lists/type',
			'text/type' => 'text/type',
			'text/lists/type' => 'text/lists/type',
		],
	],
];
